version: '3'
services:
  mysql-db:
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: poc-nest-typeorm-double-pfk
    ports:
      - "3306:3306"
  
  adminer:    
    image: adminer
    restart: always
    depends_on: 
      - mysql-db
    ports:      
      - "8080:8080"